version: "3.8"
services:
  db:
    container_name: mysql_server
    image: mysql/mysql-server:latest
    environment:
      MYSQL_HOST_AUTH_METHOD: trust
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      # - ./mysql_init/1.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql_init/:/docker-entrypoint-initdb.d/
      - ./data_for_mysql/:/var/lib/mysql-files/data/

      # - ./volumeToAttach:/mysqldb
    #   # - ./var/lib/mysql-files:/var/lib/mysql-files/
    ports:
      - '3305:3305'
    networks:
      network_ml:
        ipv4_address: 10.5.0.5

  sqlpad:
    container_name: mysqlpad_ml
    image: sqlpad/sqlpad:master
    depends_on:
      - db
    environment:
      # SQLPAD_ADMIN: admin@sql.pad
      # SQLPAD_ADMIN_PASSWORD: password1234
      SQLPAD_CONFIG: /myConfig.env
      # SQLPAD_CONNECTIONS__mysqlpad_ml__name="pickle"
    ports:
      - '3000:3000'
    volumes:
      - ./sqlpad_env_file/my.env:/myConfig.env
    #   - ./ml_space:/sqlpad
    networks:
      network_ml:
        ipv4_address: 10.5.0.6

networks:
  network_ml:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1